# Generated by Django 2.0 on 2020-12-23 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='附件')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('html', models.TextField(blank=True, null=True, verbose_name='HTML')),
                ('md', models.TextField(blank=True, null=True, verbose_name='Markdown格式')),
                ('link', models.URLField(blank=True, null=True, verbose_name='文档链接')),
                ('attachments', models.ManyToManyField(blank=True, related_name='doc_attachments', to='mdoc.Attachment', verbose_name='附件')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mdoc_doc_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '2.文档',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
            ],
            options={
                'verbose_name': '分档分类',
                'verbose_name_plural': '分档分类',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mdoc_doclibrary_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mdoc_doclibrary_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '文档库',
                'verbose_name_plural': '1.文档库',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='doccategory',
            name='doc_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doccategory_category', to='mdoc.DocLibrary', verbose_name='文档库'),
        ),
        migrations.AddField(
            model_name='doccategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mdoc_doccategory_parent', to='mdoc.DocCategory', verbose_name='父级对象'),
        ),
        migrations.AddField(
            model_name='doc',
            name='doc_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_category', to='mdoc.DocCategory', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='doc',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mdoc_doc_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='doc',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
