# Generated by Django 4.0.5 on 2023-06-01 13:25

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('mdoc', '0001_initial'),
        ('mproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_project', to='mproject.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='doc',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
