# Generated by Django 2.0 on 2020-12-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'ordering': ['id'], 'verbose_name': '文档', 'verbose_name_plural': '文档'},
        ),
        migrations.AlterModelOptions(
            name='doclibrary',
            options={'ordering': ['id'], 'verbose_name': '文档库', 'verbose_name_plural': '文档库'},
        ),
    ]
