# Generated by Django 2.0 on 2020-12-23 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mproduct', '0003_auto_20201223_1805'),
        ('mproject', '0009_auto_20201223_1752'),
        ('mdoc', '0002_auto_20201223_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='附件')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='doc',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='html',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='md',
        ),
        migrations.AddField(
            model_name='doc',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='文档正文'),
        ),
        migrations.AddField(
            model_name='doc',
            name='doc_library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mdoc_doc_doc_library', to='mdoc.DocLibrary', verbose_name='所属分类'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mdoc_doc_product', to='mproduct.Product', verbose_name='所属产品'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='doc_project', to='mproject.Project', verbose_name='所属项目'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='文档备注'),
        ),
        migrations.AddField(
            model_name='doc',
            name='type',
            field=models.CharField(choices=[('func_test', '功能测试阶段'), ('integrate_test', '集成测试阶段'), ('sys_test', '系统测试阶段'), ('unit_test', '单元测试阶段'), ('smoke_test', '冒烟测试阶段'), ('version_verify', '版本验证阶段')], default='func_test', max_length=20, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='doc_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mdoc_doc_doc_category', to='mdoc.DocCategory', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='doccategory',
            name='doc_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mdoc_doccategory_doc_library', to='mdoc.DocLibrary', verbose_name='文档库'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
