# Generated by Django 2.0 on 2020-12-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdoc', '0003_auto_20201223_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='remarks',
        ),
    ]
