# Generated by Django 2.0 on 2020-12-24 03:09

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdoc', '0005_auto_20201223_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='文档正文'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='description',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='doclibrary',
            name='description',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='描述'),
        ),
    ]
