# Generated by Django 4.0.5 on 2022-06-27 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mproduct', '0005_alter_product_creator_alter_product_operator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mproject', '0010_auto_20201224_1109'),
        ('mdoc', '0006_auto_20201224_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='doc_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_doc_category', to='mdoc.doccategory', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='doc_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_doc_library', to='mdoc.doclibrary', verbose_name='所属文档库'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_product', to='mproduct.product', verbose_name='所属产品'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_project', to='mproject.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='doccategory',
            name='doc_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_doc_library', to='mdoc.doclibrary', verbose_name='文档库'),
        ),
        migrations.AlterField(
            model_name='doccategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_parent', to='mdoc.doccategory', verbose_name='父级对象'),
        ),
        migrations.AlterField(
            model_name='doclibrary',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='doclibrary',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
    ]
