# Generated by Django 2.0 on 2020-12-22 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utils.field_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('mproduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='序号')),
                ('excepted', models.CharField(blank=True, max_length=200, null=True, verbose_name='期望结果')),
            ],
            options={
                'verbose_name': '步骤',
                'verbose_name_plural': '步骤',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'PO'), (1, 'P1'), (2, 'P2'), (3, 'P3'), (4, 'P4'), (5, 'P5')], default=2, verbose_name='优先级')),
                ('status', models.CharField(choices=[('ok', '正常'), ('error', '异常'), ('pass', '通过'), ('fail', '失败')], default='ok', max_length=20, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('stage', models.CharField(choices=[('dev', '开发阶段'), ('test', '测试环境测试'), ('stage', '预发测试'), ('prod', '线上测试')], default='prod', max_length=20, verbose_name='适用阶段')),
                ('pre_condition', models.TextField(blank=True, verbose_name='预置条件')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mtest_testcase_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcase_module', to='mproduct.ProductModule', verbose_name='所属模块')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mtest_testcase_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='testcase_product', to='mproduct.Product', verbose_name='所属产品')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '3.测试用例',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', '正常'), ('error', '异常'), ('pass', '通过'), ('fail', '失败')], default='ok', max_length=20, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('data', utils.field_utils.YamlField(blank=True, null=True, verbose_name='测试结果数据')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcaserecord_test_case', to='mtest.TestCase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试用例记录',
                'verbose_name_plural': '测试用例记录',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('options', utils.field_utils.YamlField(blank=True, null=True, verbose_name='运行参数')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mtest_testplan_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testplan_module', to='mproduct.ProductModule', verbose_name='所属模块')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mtest_testplan_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='testplan_product', to='mproduct.Product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '2.测试计划',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestPlanSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='顺序')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='testplansolution_test_case', to='mtest.TestCase', verbose_name='测试用例')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testplansolution_test_plan', to='mtest.TestPlan', verbose_name='测试计划')),
            ],
            options={
                'verbose_name': '测试方案',
                'verbose_name_plural': '测试方案',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', '正常'), ('error', '异常'), ('pass', '通过'), ('fail', '失败')], default='ok', max_length=20, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('data', utils.field_utils.YamlField(blank=True, null=True, verbose_name='测试结果数据')),
                ('html', models.TextField(blank=True, null=True, verbose_name='测试报告')),
                ('logs', models.TextField(blank=True, null=True, verbose_name='测试日志')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testreport_test_plan', to='mtest.TestPlan', verbose_name='所属测试计划')),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '4.测试报告',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='testplan',
            name='test_cases',
            field=models.ManyToManyField(blank=True, through='mtest.TestPlanSolution', to='mtest.TestCase'),
        ),
        migrations.AddField(
            model_name='testcaserecord',
            name='test_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcaserecord_test_report', to='mtest.TestReport', verbose_name='所属测试报告'),
        ),
        migrations.AddField(
            model_name='step',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_test_case', to='mtest.TestCase', verbose_name='测试用例'),
        ),
    ]
