# Generated by Django 4.0.5 on 2023-06-01 11:03

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teststep',
            options={'ordering': ['id'], 'verbose_name': '测试步骤', 'verbose_name_plural': '测试步骤'},
        ),
        migrations.AlterField(
            model_name='bug',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'P0'), (1, 'P1'), (2, 'P2'), (3, 'P3'), (4, 'P4'), (5, 'P5')], default=2, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='type',
            field=models.CharField(choices=[('code', '代码错误'), ('ui', '界面优化'), ('design', '设计缺陷'), ('conf', '配置相关'), ('deploy', '安装部署'), ('secure', '安全相关'), ('performance', '性能问题'), ('standard', '标准规范'), ('test_script', '测试脚本'), ('else', '其他')], default='code', max_length=20, verbose_name='用例类型'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'P0'), (1, 'P1'), (2, 'P2'), (3, 'P3'), (4, 'P4'), (5, 'P5')], default=2, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='pre_condition',
            field=tinymce.models.HTMLField(blank=True, verbose_name='预置条件'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'P0'), (1, 'P1'), (2, 'P2'), (3, 'P3'), (4, 'P4'), (5, 'P5')], default=2, verbose_name='优先级'),
        ),
    ]
