# Generated by Django 4.0.5 on 2023-06-02 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtest', '0002_alter_bug_status_alter_bug_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAttachment',
        ),
    ]
