# Generated by Django 2.0 on 2020-12-23 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mproduct', '0002_auto_20201223_1153'),
        ('mtest', '0002_auto_20201223_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='related_release',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='related_release',
        ),
        migrations.AddField(
            model_name='bug',
            name='related_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mtest_bug_related_release', to='mproduct.ProductVersion', verbose_name='影响版本'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='related_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mtest_testplan_related_version', to='mproduct.ProductVersion', verbose_name='关联版本'),
        ),
    ]
