# Generated by Django 4.0.5 on 2023-06-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtest', '0002_alter_teststep_options_alter_bug_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='type',
            field=models.CharField(choices=[('func_test', '功能'), ('perf_test', '性能'), ('conf_test', '配置相关'), ('deploy_test', '安装部署'), ('sec_test', '安全相关'), ('api_test', '接口测试'), ('else', '其他')], default='func_test', max_length=20, verbose_name='用例类型'),
        ),
    ]
