# Generated by Django 2.0 on 2020-12-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtest', '0003_auto_20201223_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['id'], 'verbose_name': '测试用例', 'verbose_name_plural': '测试用例'},
        ),
        migrations.AlterModelOptions(
            name='testplan',
            options={'ordering': ['id'], 'verbose_name': '测试计划', 'verbose_name_plural': '测试计划'},
        ),
        migrations.AlterModelOptions(
            name='testplancase',
            options={'ordering': ['id'], 'verbose_name': '测试用例', 'verbose_name_plural': '测试用例'},
        ),
        migrations.AddField(
            model_name='testplan',
            name='test_summary',
            field=models.TextField(blank=True, null=True, verbose_name='测试总结'),
        ),
    ]
