# Generated by Django 2.0 on 2020-12-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtest', '0006_auto_20201223_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='status',
            field=models.CharField(blank=True, choices=[('new', '激活'), ('resolved', '已解决'), ('closed', '已关闭')], max_length=20, null=True, verbose_name='状态'),
        ),
    ]
