# Generated by Django 2.0 on 2020-12-24 03:09

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtest', '0007_bug_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['id'], 'verbose_name': '缺陷', 'verbose_name_plural': '缺陷'},
        ),
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('new', '激活'), ('resolved', '已解决'), ('closed', '已关闭')], default='new', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='description',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='description',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='test_summary',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='测试总结'),
        ),
    ]
