# Generated by Django 4.0.5 on 2023-06-01 13:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mproduct', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='描述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='结束日期')),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='项目代号')),
                ('type', models.CharField(blank=True, choices=[('short', '短期项目'), ('long', '长期项目'), ('ops', '运维项目')], max_length=20, null=True, verbose_name='项目类型')),
                ('work_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='可用工作日')),
                ('team_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='团队名称')),
                ('status', models.CharField(blank=True, choices=[('new', '未开始'), ('processing', '进行中'), ('hang_up', '已挂起'), ('done', '已完成')], default='new', max_length=20, null=True, verbose_name='项目状态')),
                ('view_control', models.CharField(choices=[('default', '默认'), ('private', '私有'), ('white_list', '白名单')], default='default', max_length=20, verbose_name='访问控制')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='描述')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'P0'), (1, 'P1'), (2, 'P2'), (3, 'P3'), (4, 'P4'), (5, 'P5')], default=2, verbose_name='优先级')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='结束日期')),
                ('type', models.CharField(choices=[('dev', '开发任务'), ('test', '测试任务')], default='', max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(blank=True, choices=[('new', '未开始'), ('processing', '进行中'), ('hang_up', '已挂起'), ('done', '已完成')], default='new', max_length=20, null=True, verbose_name='项目状态')),
                ('estimated_time', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='预计耗时(h)')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_assignee', to=settings.AUTH_USER_MODEL, verbose_name='指派给')),
                ('cc_to', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_cc_to', to=settings.AUTH_USER_MODEL, verbose_name='抄送给')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('product_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_module', to='mproduct.productmodule', verbose_name='所属模块')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_project', to='mproject.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='附件')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_task', to='mproject.task', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='描述')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'P0'), (1, 'P1'), (2, 'P2'), (3, 'P3'), (4, 'P4'), (5, 'P5')], default=2, verbose_name='优先级')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('source', models.CharField(blank=True, choices=[('customer', '客户'), ('user', '用户'), ('pm', '产品经理'), ('market', '市场'), ('customer_service', '客服'), ('developer', '开发人员'), ('tester', '测试人员'), ('else', '其他')], max_length=20, null=True, verbose_name='需求来源')),
                ('status', models.CharField(choices=[('active', '激活'), ('closed', '关闭')], default='active', max_length=20, verbose_name='状态')),
                ('stage', models.CharField(choices=[('new', '未开始'), ('in_plan', '已计划'), ('in_project', '已立项'), ('developing', '研发中'), ('develop_complete', '研发完毕'), ('testing', '测试中'), ('test_complete', '测试完毕'), ('accepted', '已验收'), ('online', '已发布')], default='new', max_length=20, verbose_name='所处阶段')),
                ('no_need_review', models.BooleanField(default=True, verbose_name='不需要评审')),
                ('estimated_time', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='预计耗时(h)')),
                ('acceptance_criteria', tinymce.models.HTMLField(blank=True, null=True, verbose_name='验收标准')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_assignee', to=settings.AUTH_USER_MODEL, verbose_name='指派给')),
                ('cc_to', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_cc_to', to=settings.AUTH_USER_MODEL, verbose_name='抄送给')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_product', to='mproduct.product', verbose_name='所属产品')),
                ('product_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_module', to='mproduct.productmodule', verbose_name='所属模块')),
                ('product_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_plan', to='mproduct.productplan', verbose_name='所属计划')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='由谁评审')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': '需求',
                'verbose_name_plural': '需求',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRelatedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_product', to='mproduct.product', verbose_name='所属产品')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_project', to='mproject.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '关联产品',
                'verbose_name_plural': '关联产品',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='角色')),
                ('work_days', models.FloatField(default=66, verbose_name='可用工日')),
                ('work_hours_per_day', models.FloatField(default=7, verbose_name='可用工时/每天')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_project', to='mproject.project', verbose_name='所属项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_members', through='mproject.ProjectMember', to=settings.AUTH_USER_MODEL, verbose_name='项目成员'),
        ),
        migrations.AddField(
            model_name='project',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='project',
            name='product_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_product_manager', to=settings.AUTH_USER_MODEL, verbose_name='产品负责人'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_manager', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人'),
        ),
        migrations.AddField(
            model_name='project',
            name='related_products',
            field=models.ManyToManyField(blank=True, through='mproject.ProjectRelatedProduct', to='mproduct.product', verbose_name='关联产品'),
        ),
        migrations.AddField(
            model_name='project',
            name='release_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_release_manager', to=settings.AUTH_USER_MODEL, verbose_name='发布负责人'),
        ),
        migrations.AddField(
            model_name='project',
            name='test_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_test_manager', to=settings.AUTH_USER_MODEL, verbose_name='测试负责人'),
        ),
        migrations.CreateModel(
            name='ProductRequirementAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='附件')),
                ('product_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_product_requirement', to='mproject.requirement', verbose_name='所属需求')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'ordering': ['id'],
            },
        ),
    ]
