# Generated by Django 2.0 on 2020-12-23 03:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mproduct', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='结束日期')),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='项目代号')),
                ('work_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='可用工作日')),
                ('team_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='团队名称')),
                ('type', models.CharField(choices=[('short', '短期项目'), ('long', '长期项目'), ('ops', '运维项目')], default='', max_length=20, verbose_name='项目类型')),
                ('view_control', models.CharField(choices=[('default', '默认'), ('private', '私有'), ('white_list', '白名单')], default='default', max_length=20, verbose_name='访问控制')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mproject_project_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '1.项目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='角色')),
                ('work_days', models.FloatField(default=66, verbose_name='可用工日')),
                ('work_hours_per_day', models.FloatField(default=7, verbose_name='可用工时/每天')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projectmember_project', to='mproject.Project', verbose_name='所属项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mproject_projectmember_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRelatedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mproject_projectrelatedproduct_product', to='mproduct.Product', verbose_name='所属产品')),
                ('product_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectrelatedproduct_product_branch', to='mproduct.ProductBranch', verbose_name='所属分支')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projectrelatedproduct_project', to='mproject.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '关联产品',
                'verbose_name_plural': '关联产品',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'O'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=2, verbose_name='优先级')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='结束日期')),
                ('type', models.CharField(choices=[('dev', '开发任务'), ('test', '测试任务')], default='', max_length=20, verbose_name='任务类型')),
                ('estimated_time', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='预计耗时(h)')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mproject_task_assignee', to=settings.AUTH_USER_MODEL, verbose_name='指派给')),
                ('cc_to', models.ManyToManyField(blank=True, related_name='mproject_task_cc_to', to=settings.AUTH_USER_MODEL, verbose_name='抄送给')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mproject_task_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mproject_task_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('product_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mproject_task_module', to='mproduct.ProductModule', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '4.任务',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='附件')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mproject_taskattachment_task', to='mproject.Task', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='mproject_project_members', through='mproject.ProjectMember', to=settings.AUTH_USER_MODEL, verbose_name='项目成员'),
        ),
        migrations.AddField(
            model_name='project',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mproject_project_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='project',
            name='related_products',
            field=models.ManyToManyField(blank=True, through='mproject.ProjectRelatedProduct', to='mproduct.Product', verbose_name='关联产品'),
        ),
    ]
