# Generated by Django 4.0.5 on 2023-06-02 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskattachment',
            name='task',
        ),
        migrations.DeleteModel(
            name='ProductRequirementAttachment',
        ),
        migrations.DeleteModel(
            name='TaskAttachment',
        ),
    ]
