# Generated by Django 2.0 on 2020-12-23 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mproject', '0002_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='product_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mproject_project_product_manager', to=settings.AUTH_USER_MODEL, verbose_name='产品负责人'),
        ),
        migrations.AddField(
            model_name='project',
            name='release_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mproject_project_release_manager', to=settings.AUTH_USER_MODEL, verbose_name='发布负责人'),
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('short', '短期项目'), ('long', '长期项目'), ('ops', '运维项目')], default='', max_length=20, verbose_name='项目类型'),
        ),
        migrations.AddField(
            model_name='project',
            name='test_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mproject_project_test_manager', to=settings.AUTH_USER_MODEL, verbose_name='测试负责人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('short', '短期项目'), ('long', '长期项目'), ('ops', '运维项目')], max_length=20, null=True, verbose_name='项目类型'),
        ),
    ]
