# Generated by Django 2.0 on 2020-12-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mproject', '0003_auto_20201223_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('short', '短期项目'), ('long', '长期项目'), ('ops', '运维项目')], default='', max_length=20, verbose_name='项目状态'),
        ),
    ]
