# Generated by Django 2.0 on 2020-12-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mproject', '0004_auto_20201223_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(blank=True, choices=[('short', '短期项目'), ('long', '长期项目'), ('ops', '运维项目')], default='new', max_length=20, null=True, verbose_name='项目状态'),
        ),
    ]
