# Generated by Django 2.0 on 2020-12-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mproject', '0006_auto_20201223_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='stage',
            new_name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('new', '未开始'), ('processing', '进行中'), ('hang_up', '已挂起'), ('done', '已完成')], default='new', max_length=20, null=True, verbose_name='项目状态'),
        ),
    ]
