# Generated by Django 2.0 on 2020-12-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mproject', '0008_task_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id'], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id'], 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
    ]
