# Generated by Django 2.0 on 2020-12-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('normal', '正常'), ('multi_branches', '多分支'), ('multi_platforms', '多平台')], max_length=20, null=True, verbose_name='产品类型'),
        ),
    ]
