# Generated by Django 4.0.5 on 2023-06-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequirement',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'P0'), (1, 'P1'), (2, 'P2'), (3, 'P3'), (4, 'P4'), (5, 'P5')], default=2, verbose_name='优先级'),
        ),
    ]
