# Generated by Django 2.0 on 2020-12-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mproduct', '0002_auto_20201223_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrelease',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='打包日期'),
        ),
        migrations.AddField(
            model_name='productrelease',
            name='status',
            field=models.CharField(choices=[('ok', '正常'), ('停止维护', '停止维护')], default='ok', max_length=20, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='build_date',
            field=models.DateField(blank=True, null=True, verbose_name='打包日期'),
        ),
    ]
