# Generated by Django 4.0.5 on 2023-06-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mproduct', '0002_alter_productrequirement_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequirement',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='productrequirement',
            name='cc_to',
        ),
        migrations.RemoveField(
            model_name='productrequirement',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='productrequirement',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='productrequirement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productrequirement',
            name='product_branch',
        ),
        migrations.RemoveField(
            model_name='productrequirement',
            name='product_module',
        ),
        migrations.RemoveField(
            model_name='productrequirement',
            name='product_plan',
        ),
        migrations.RemoveField(
            model_name='productrequirement',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='productrequirement',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='productrequirementattachment',
            name='product_requirement',
        ),
        migrations.AlterModelOptions(
            name='productplan',
            options={'ordering': ['id'], 'verbose_name': '发布计划', 'verbose_name_plural': '发布计划'},
        ),
        migrations.AlterModelOptions(
            name='productversion',
            options={'ordering': ['id'], 'verbose_name': '版本', 'verbose_name_plural': '版本'},
        ),
    ]
