# Generated by Django 4.0.5 on 2023-06-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mproduct', '0003_remove_productrequirement_assignee_and_more'),
        ('mtest', '0004_alter_bug_related_requirement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRequirement',
        ),
        migrations.DeleteModel(
            name='ProductRequirementAttachment',
        ),
    ]
